// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// Paymenttype is the predicate function for paymenttype builders.
type Paymenttype func(*sql.Selector)

// Roomtype is the predicate function for roomtype builders.
type Roomtype func(*sql.Selector)
