// Code generated by entc, DO NOT EDIT.

package payment

const (
	// Label holds the string label denoting the payment type in the database.
	Label = "payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPAYDAY holds the string denoting the payday field in the database.
	FieldPAYDAY = "payday"

	// EdgeCustomer holds the string denoting the customer edge name in mutations.
	EdgeCustomer = "customer"
	// EdgeEmployee holds the string denoting the employee edge name in mutations.
	EdgeEmployee = "employee"
	// EdgePaymenttype holds the string denoting the paymenttype edge name in mutations.
	EdgePaymenttype = "paymenttype"
	// EdgeRoomtype holds the string denoting the roomtype edge name in mutations.
	EdgeRoomtype = "roomtype"

	// Table holds the table name of the payment in the database.
	Table = "payments"
	// CustomerTable is the table the holds the customer relation/edge.
	CustomerTable = "payments"
	// CustomerInverseTable is the table name for the Customer entity.
	// It exists in this package in order to avoid circular dependency with the "customer" package.
	CustomerInverseTable = "customers"
	// CustomerColumn is the table column denoting the customer relation/edge.
	CustomerColumn = "customer_payment"
	// EmployeeTable is the table the holds the employee relation/edge.
	EmployeeTable = "payments"
	// EmployeeInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	EmployeeInverseTable = "employees"
	// EmployeeColumn is the table column denoting the employee relation/edge.
	EmployeeColumn = "employee_payment"
	// PaymenttypeTable is the table the holds the paymenttype relation/edge.
	PaymenttypeTable = "payments"
	// PaymenttypeInverseTable is the table name for the Paymenttype entity.
	// It exists in this package in order to avoid circular dependency with the "paymenttype" package.
	PaymenttypeInverseTable = "paymenttypes"
	// PaymenttypeColumn is the table column denoting the paymenttype relation/edge.
	PaymenttypeColumn = "paymenttype_payment"
	// RoomtypeTable is the table the holds the roomtype relation/edge.
	RoomtypeTable = "payments"
	// RoomtypeInverseTable is the table name for the Roomtype entity.
	// It exists in this package in order to avoid circular dependency with the "roomtype" package.
	RoomtypeInverseTable = "roomtypes"
	// RoomtypeColumn is the table column denoting the roomtype relation/edge.
	RoomtypeColumn = "roomtype_payment"
)

// Columns holds all SQL columns for payment fields.
var Columns = []string{
	FieldID,
	FieldPAYDAY,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Payment type.
var ForeignKeys = []string{
	"customer_payment",
	"employee_payment",
	"paymenttype_payment",
	"roomtype_payment",
}
