// Code generated by entc, DO NOT EDIT.

package employee

const (
	// Label holds the string label denoting the employee type in the database.
	Label = "employee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEMPLOYEENAME holds the string denoting the employeename field in the database.
	FieldEMPLOYEENAME = "employeename"
	// FieldEMPLOYEEPASSWORD holds the string denoting the employeepassword field in the database.
	FieldEMPLOYEEPASSWORD = "employeepassword"

	// EdgePayment holds the string denoting the payment edge name in mutations.
	EdgePayment = "payment"

	// Table holds the table name of the employee in the database.
	Table = "employees"
	// PaymentTable is the table the holds the payment relation/edge.
	PaymentTable = "payments"
	// PaymentInverseTable is the table name for the Payment entity.
	// It exists in this package in order to avoid circular dependency with the "payment" package.
	PaymentInverseTable = "payments"
	// PaymentColumn is the table column denoting the payment relation/edge.
	PaymentColumn = "employee_payment"
)

// Columns holds all SQL columns for employee fields.
var Columns = []string{
	FieldID,
	FieldEMPLOYEENAME,
	FieldEMPLOYEEPASSWORD,
}
