// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/witsarut7/app/ent/roomtype"
)

// Roomtype is the model entity for the Roomtype schema.
type Roomtype struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ROOMPRICE holds the value of the "ROOMPRICE" field.
	ROOMPRICE int `json:"ROOMPRICE,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoomtypeQuery when eager-loading is set.
	Edges RoomtypeEdges `json:"edges"`
}

// RoomtypeEdges holds the relations/edges for other nodes in the graph.
type RoomtypeEdges struct {
	// Payment holds the value of the payment edge.
	Payment []*Payment
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PaymentOrErr returns the Payment value or an error if the edge
// was not loaded in eager-loading.
func (e RoomtypeEdges) PaymentOrErr() ([]*Payment, error) {
	if e.loadedTypes[0] {
		return e.Payment, nil
	}
	return nil, &NotLoadedError{edge: "payment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Roomtype) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullInt64{}, // ROOMPRICE
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Roomtype fields.
func (r *Roomtype) assignValues(values ...interface{}) error {
	if m, n := len(values), len(roomtype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	r.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field ROOMPRICE", values[0])
	} else if value.Valid {
		r.ROOMPRICE = int(value.Int64)
	}
	return nil
}

// QueryPayment queries the payment edge of the Roomtype.
func (r *Roomtype) QueryPayment() *PaymentQuery {
	return (&RoomtypeClient{config: r.config}).QueryPayment(r)
}

// Update returns a builder for updating this Roomtype.
// Note that, you need to call Roomtype.Unwrap() before calling this method, if this Roomtype
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Roomtype) Update() *RoomtypeUpdateOne {
	return (&RoomtypeClient{config: r.config}).UpdateOne(r)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (r *Roomtype) Unwrap() *Roomtype {
	tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Roomtype is not a transactional entity")
	}
	r.config.driver = tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Roomtype) String() string {
	var builder strings.Builder
	builder.WriteString("Roomtype(")
	builder.WriteString(fmt.Sprintf("id=%v", r.ID))
	builder.WriteString(", ROOMPRICE=")
	builder.WriteString(fmt.Sprintf("%v", r.ROOMPRICE))
	builder.WriteByte(')')
	return builder.String()
}

// Roomtypes is a parsable slice of Roomtype.
type Roomtypes []*Roomtype

func (r Roomtypes) config(cfg config) {
	for _i := range r {
		r[_i].config = cfg
	}
}
