// Code generated by entc, DO NOT EDIT.

package customer

const (
	// Label holds the string label denoting the customer type in the database.
	Label = "customer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUSERNAME holds the string denoting the username field in the database.
	FieldUSERNAME = "username"

	// EdgePayment holds the string denoting the payment edge name in mutations.
	EdgePayment = "payment"

	// Table holds the table name of the customer in the database.
	Table = "customers"
	// PaymentTable is the table the holds the payment relation/edge.
	PaymentTable = "payments"
	// PaymentInverseTable is the table name for the Payment entity.
	// It exists in this package in order to avoid circular dependency with the "payment" package.
	PaymentInverseTable = "payments"
	// PaymentColumn is the table column denoting the payment relation/edge.
	PaymentColumn = "customer_payment"
)

// Columns holds all SQL columns for customer fields.
var Columns = []string{
	FieldID,
	FieldUSERNAME,
}
